### ISSUE TITLE
PHP 8.0/8.1 Compatibility issue: Critical error when cost in range is empty if Standard room rate is empty as well

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-accommodation-bookings#296]
#### Affected ticket(s)

5311290-zen

When we add a range under Rates tab for an Accommodation product - a critical error is triggered if the cost in range is empty and if the Standard room rate is not set.

![image](https://d.pr/i/Jwz8LZ+)

#### Steps to reproduce the issue

1. Install the latest versions of Bookings and Accommodation Bookings on a site with PHP 8/8.1
2. Add an Accommodation Bookings product
3. Go to **Rates** tab and add a range (Range of months for example)
4. Keep the Standard room rate empty, and also the cost as empty.
5. Update/Publish the product and check the **Rates** tab again

```
2022-06-20T13:29:14+00:00 CRITICAL Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php:112
Stack trace:
#0 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php(112): abs()
#1 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates.php(46): include('...')
#2 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-panels.php(93): include('...')
#3 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-includes/class-wp-hook.php(307): WC_Accommodation_Booking_Admin_Panels->panels()
#4 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php(53): do_action()
#7 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include('...')
#8 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-admin/includes/template.php(1401): WC_Meta_Box_Product_Data::output()
#9 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-admin/edit-form-advanced.php(688): do_meta_boxes()
#10 /var/www/wooturnkey/public_html/sites/wp-1847562/wp-admin/post.php(206): require('...')
#11 {main}
  thrown in /var/www/wooturnkey/public_html/sites/wp-1847562/wp-content/plugins/woocommerce-accommodation-bookings/includes/admin/views/html-accommodation-booking-rates-fields.php on line 112
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by Brianmitchtay** [comment]
Seeing this come up again in 5456421-zen. Advising them to revert PHP versions til a fix is released. This worked for them.
